[package]
name = "test-notification"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fcm = "0.9.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
